import { useEffect, useMemo, useRef, useState } from 'react';

const STORE = 'metal-tinder-datasets-v1';
const load = () => { try { return JSON.parse(localStorage.getItem(STORE)) || []; } catch { return []; } };
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const toDataUrl = file => new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(r.result); r.onerror = reject; r.readAsDataURL(file); });
const formatTime = seconds => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
const statusLabel = status => status === 'complete' ? 'Complete' : status === 'recording' ? 'Recording' : 'Pending';

function App() {
  const [datasets, setDatasets] = useState(load);
  const [screen, setScreen] = useState({ name: 'home' });
  const [notice, setNotice] = useState('');
  useEffect(() => localStorage.setItem(STORE, JSON.stringify(datasets)), [datasets]);
  useEffect(() => { if (!notice) return; const id = setTimeout(() => setNotice(''), 2600); return () => clearTimeout(id); }, [notice]);
  const dataset = datasets.find(d => d.id === screen.datasetId);
  const updateDataset = next => setDatasets(all => all.map(d => d.id === next.id ? next : d));
  const deleteDataset = id => { if (confirm('Delete this dataset and all its samples?')) { setDatasets(all => all.filter(d => d.id !== id)); setScreen({ name: 'home' }); setNotice('Dataset deleted'); } };

  return <main className="app-shell">
    {screen.name === 'home' && <Home datasets={datasets} onCreate={() => setScreen({ name: 'create' })} onOpen={id => setScreen({ name: 'overview', datasetId: id })} onRename={(id, name) => setDatasets(all => all.map(d => d.id === id ? { ...d, name } : d))} onDelete={deleteDataset} />}
    {screen.name === 'create' && <Create onBack={() => setScreen({ name: 'home' })} onCreate={created => { setDatasets(all => [...all, created]); setScreen({ name: 'overview', datasetId: created.id }); }} />}
    {screen.name === 'overview' && dataset && <Overview dataset={dataset} onBack={() => setScreen({ name: 'home' })} onUpdate={updateDataset} onDelete={() => deleteDataset(dataset.id)} onOpenSample={sampleId => setScreen({ name: 'sample', datasetId: dataset.id, sampleId })} />}
    {screen.name === 'sample' && dataset && <SampleDetail dataset={dataset} sampleId={screen.sampleId} onBack={() => setScreen({ name: 'overview', datasetId: dataset.id })} onUpdate={updateDataset} />}
    {notice && <div className="toast">{notice}</div>}
  </main>;
}

function Header({ title, back, action }) { return <header className="topbar">{back ? <button className="icon-button" onClick={back} aria-label="Go back">←</button> : <div className="brand-mark">M</div>}<h1>{title}</h1>{action || <span className="header-space" />}</header>; }
function Progress({ value }) { return <div className="progress"><span style={{ width: `${value * 100}%` }} /></div>; }

function Home({ datasets, onCreate, onOpen, onRename, onDelete }) {
  return <><Header title="Datasets" action={<button className="text-button" onClick={onCreate}>+ New</button>} /><section className="page home-page">
    <div className="hero"><div><p className="eyebrow">METAL TINDER</p><h2>Capture better training data.</h2><p>Pair your images with spoken descriptions, right from your phone.</p></div><button className="primary-button desktop-create" onClick={onCreate}>＋ Create dataset</button></div>
    {datasets.length === 0 ? <div className="empty"><div className="empty-icon">▣</div><h3>No datasets yet</h3><p>Import images and record a description for every sample.</p><button className="primary-button" onClick={onCreate}>Create dataset</button></div> : <div className="dataset-list">{datasets.map(dataset => { const total = dataset.samples.length; const done = dataset.samples.filter(s => s.status === 'complete').length; return <article className="dataset-card" key={dataset.id} onClick={() => onOpen(dataset.id)}><div className="dataset-icon">▣</div><div className="dataset-copy"><h3>{dataset.name}</h3><p>{done} of {total} annotated · {dataset.category || 'Industrial'}</p><Progress value={total ? done / total : 0} /></div><div className="card-menu" onClick={e => e.stopPropagation()}><button className="icon-button" aria-label="Dataset actions" onClick={() => { const result = prompt('Rename dataset', dataset.name); if (result?.trim()) onRename(dataset.id, result.trim()); }}>•••</button><button className="delete-link" onClick={() => onDelete(dataset.id)}>Delete</button></div></article>; })}</div>}
  </section><button className="fab" onClick={onCreate} aria-label="Create dataset">＋</button></>;
}

function Create({ onBack, onCreate }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState('Industrial'); const [language, setLanguage] = useState('English'); const [images, setImages] = useState([]); const [error, setError] = useState('');
  const pick = async event => { const files = [...event.target.files]; if (!files.length) return; const newImages = await Promise.all(files.map(async f => ({ id: uid(), name: f.name, image: await toDataUrl(f), status: 'pending', language: 'en', notes: '', transcript: '', audio: null, duration: 0 }))); setImages(old => [...old, ...newImages]); event.target.value = ''; };
  const create = () => { if (name.trim().length < 3) return setError('Use at least 3 characters for the dataset name.'); if (!images.length) return setError('Add at least one image before creating the dataset.'); onCreate({ id: uid(), name: name.trim(), description, category, language, created: new Date().toISOString(), samples: images }); };
  return <><Header title="Create Dataset" back={onBack} action={<button className="text-button" onClick={() => alert('Import images, then record a spoken description for each sample.')}>Guide</button>} /><section className="page create-page"><div className="intro"><div className="intro-icon">◈</div><div><h2>Build a new audio dataset</h2><p>Set up your dataset details and import the images that will become recording samples.</p></div></div><div className="steps"><b>01 <span>Dataset details</span></b><i>›</i><b>02 <span>Import images</span></b><i>›</i><b>03 <span>Start annotating</span></b></div><div className="create-grid"><section className="panel"><h3>✎ Dataset details</h3><p>Give your dataset a clear identity.</p><label>Dataset name <em>*</em><input value={name} maxLength="60" onChange={e => setName(e.target.value)} placeholder="e.g. Industrial Machine Sounds" /></label><label>Description<textarea value={description} maxLength="240" onChange={e => setDescription(e.target.value)} placeholder="What is this dataset being created for?" /></label><div className="two-col"><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{['Industrial','Urban','Nature','Vehicles','Other'].map(x => <option key={x}>{x}</option>)}</select></label><label>Language<select value={language} onChange={e => setLanguage(e.target.value)}>{['English','Tamil','Hindi','Malayalam','Other'].map(x => <option key={x}>{x}</option>)}</select></label></div><div className="metadata"> <span>✓</span><div><b>Keep metadata with samples</b><small>Store filename, language and recording status.</small></div></div></section><section className="panel image-panel"><h3>▧ Import images</h3><p>Add one or more images from your device.</p><label className="dropzone"><input type="file" accept="image/*" multiple onChange={pick} /><strong>Choose images</strong><span>JPG, PNG, or WebP · multiple files supported</span></label>{images.length > 0 && <><div className="image-count">{images.length} image{images.length !== 1 ? 's' : ''} ready <button onClick={() => setImages([])}>Clear all</button></div><div className="image-grid">{images.map((image, i) => <div className="thumbnail" key={image.id}><img src={image.image} alt={image.name} /><button onClick={() => setImages(all => all.filter(x => x.id !== image.id))} aria-label="Remove image">×</button><span>{String(i + 1).padStart(2, '0')}</span></div>)}</div></>}</section></div>{error && <p className="error">{error}</p>}<div className="bottom-actions"><button className="secondary-button" onClick={onBack}>Cancel</button><button className="primary-button" onClick={create}>Create dataset <span>→</span></button></div></section></>;
}

function Overview({ dataset, onBack, onUpdate, onDelete, onOpenSample }) {
  const [filter, setFilter] = useState('all'); const [adding, setAdding] = useState(false); const total = dataset.samples.length; const done = dataset.samples.filter(s => s.status === 'complete').length; const visible = dataset.samples.filter(s => filter === 'all' || s.status === filter);
  const add = async event => { const files = [...event.target.files]; const samples = await Promise.all(files.map(async f => ({ id: uid(), name: f.name, image: await toDataUrl(f), status: 'pending', language: 'en', notes: '', transcript: '', audio: null, duration: 0 }))); onUpdate({ ...dataset, samples: [...dataset.samples, ...samples] }); setAdding(false); event.target.value = ''; };
  const exportData = () => { const blob = new Blob([JSON.stringify(dataset, null, 2)], { type: 'application/json' }); const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: `${dataset.name.replace(/\s+/g, '_')}.json` }); a.click(); URL.revokeObjectURL(a.href); };
  return <><Header title={dataset.name} back={onBack} action={<button className="text-button" onClick={exportData}>Export</button>} /><section className="page overview-page"><div className="overview-hero"><div><p className="eyebrow">DATASET</p><h2>{dataset.name}</h2><p>{dataset.description || 'Ready for voice annotation.'}</p></div><button className="outline-danger" onClick={onDelete}>Delete dataset</button></div><section className="stats"><div><strong>{total}</strong><span>Images</span></div><div><strong>{done}</strong><span>Completed</span></div><div><strong>{total - done}</strong><span>To record</span></div><div><strong>{Math.round(total ? done / total * 100 : 0)}%</strong><span>Progress</span></div></section><Progress value={total ? done / total : 0} /><div className="sample-toolbar"><div className="filters">{[['all','All'],['pending','To record'],['complete','Completed']].map(([value,label]) => <button className={filter === value ? 'selected' : ''} key={value} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="secondary-button add-images">＋ Add images<input type="file" accept="image/*" multiple onChange={add} /></label></div><div className="samples">{visible.map((sample, index) => <button className="sample-card" key={sample.id} onClick={() => onOpenSample(sample.id)}><img src={sample.image} alt={sample.name} /><span className={`badge ${sample.status}`}>{statusLabel(sample.status)}</span><div><b>Sample {String(dataset.samples.indexOf(sample) + 1).padStart(2,'0')}</b><small>{sample.name}</small></div></button>)}</div>{!visible.length && <div className="empty mini"><p>No samples in this filter.</p></div>}</section></>;
}

function SampleDetail({ dataset, sampleId, onBack, onUpdate }) {
  const original = dataset.samples.find(s => s.id === sampleId); const [sample, setSample] = useState(original); const [recording, setRecording] = useState(false); const recorder = useRef(null); const chunks = useRef([]); const audioRef = useRef(null);
  const save = () => onUpdate({ ...dataset, samples: dataset.samples.map(s => s.id === sample.id ? sample : s) });
  const record = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const r = new MediaRecorder(stream); chunks.current = []; r.ondataavailable = e => chunks.current.push(e.data); r.onstop = () => { const reader = new FileReader(); reader.onload = () => { setSample(s => ({ ...s, audio: reader.result, status: 'complete' })); stream.getTracks().forEach(track => track.stop()); }; reader.readAsDataURL(new Blob(chunks.current, { type: r.mimeType || 'audio/webm' })); }; recorder.current = r; r.start(); setRecording(true); } catch { alert('Microphone access is required to make a recording.'); } };
  const stop = () => { recorder.current?.stop(); setRecording(false); };
  const remove = () => { if (confirm('Remove this sample?')) { onUpdate({ ...dataset, samples: dataset.samples.filter(s => s.id !== sample.id) }); onBack(); } };
  return <><Header title="Sample details" back={onBack} action={<button className="text-button" onClick={() => { save(); onBack(); }}>Save</button>} /><section className="page sample-page"><img className="sample-image" src={sample.image} alt={sample.name} /><div className="sample-heading"><div><p className="eyebrow">SAMPLE</p><h2>{sample.name}</h2></div><span className={`badge ${sample.status}`}>{statusLabel(sample.status)}</span></div><section className="panel"><h3>🎙 Recording</h3>{sample.audio ? <div className="audio-row"><button className="play" onClick={() => audioRef.current.paused ? audioRef.current.play() : audioRef.current.pause()}>▶</button><audio controls ref={audioRef} src={sample.audio} /><button className="secondary-button" onClick={recording ? stop : record}>{recording ? 'Stop recording' : 'Re-record'}</button></div> : <div className="record-empty"><span>◉</span><p>No audio recorded yet</p><button className={`record-button ${recording ? 'recording' : ''}`} onClick={recording ? stop : record}>{recording ? '■ Stop recording' : '● Start recording'}</button></div>}</section><section className="panel"><h3>Transcript</h3><p>Review or edit the spoken description.</p><textarea className="transcript" value={sample.transcript || ''} onChange={e => setSample(s => ({ ...s, transcript: e.target.value }))} placeholder="Spoken description text..." /></section><section className="panel"><h3>Metadata</h3><label>Language<select value={sample.language || 'en'} onChange={e => setSample(s => ({ ...s, language: e.target.value }))}><option value="en">English</option><option value="ta">Tamil</option><option value="hi">Hindi</option><option value="ml">Malayalam</option></select></label><label>Notes<textarea value={sample.notes || ''} onChange={e => setSample(s => ({ ...s, notes: e.target.value }))} placeholder="Optional notes about this sample" /></label></section><button className="outline-danger full" onClick={remove}>Remove sample</button></section></>;
}

export default App;
